#!/bin/bash
#---
## @Synopsis Perl-cpan module to generate spells from perl-cpan metadata
#---

#---
##
## @Globals QUILL_TMP_DIR
#---
function quill_get_manifests()
{
  # unless someone knows a better way to check files creation time
  # this shoud work quite well
  # basicaly update if the files are over a day old
  if [[ ! -f $QUILL_TMP_DIR/02packages.details.txt.gz ]] ||
     [[ ! -f $QUILL_TMP_DIR/03modlist.data.gz ]] ||
     [[ ! "$(find ${QUILL_TMP_DIR}/02packages.details.txt.gz -ctime 0)" == "${QUILL_TMP_DIR}/02packages.details.txt.gz" ]] ||
     [[ ! "$(find ${QUILL_TMP_DIR}/03modlist.data.gz -ctime 0)" == "${QUILL_TMP_DIR}/03modlist.data.gz" ]]
  then
    cd $QUILL_TMP_DIR
    message -n "Retrieving 02packages.details.txt.gz ... "
    wget -q \
         -O 02packages.details.txt.gz \
         ftp://ftp.perl.org/pub/CPAN/modules/02packages.details.txt.gz ||
         (error_msg "Error: unable to fetch 02packages.details.txt.gz" && return 1)
    message "done."

    message -n "Retrieving 03modlist.data.gz ... "
    wget -q \
         -O 03modlist.data.gz \
         ftp://ftp.perl.org/pub/CPAN/modules/03modlist.data.gz ||
         (error_msg "Error: unable to fetch 03modlist.data.gz" && return 1)
    message "done."
  fi
}

#---
##
## @Globals QUILL_CPAN_INFO QUILL_CPAN_METADATA
#---
function quill_get_cpan_meta(){
  eval QUILL_CPAN_INFO="( $(zgrep -w -E "^${1}" $QUILL_TMP_DIR/02packages.details.txt.gz | head -n1) )"
#  zgrep -w -E "^${1}" $QUILL_TMP_DIR/02packages.details.txt.gz | head -n1
  eval QUILL_CPAN_METADATA="( $(zgrep -w -B1 -A9 -E "^'${1}'" $QUILL_TMP_DIR/03modlist.data.gz | tr -d "[]" | sed 's:,$::g' ) )"
#  zgrep -w -B1 -A9 -E "^'${1}'" $QUILL_TMP_DIR/03modlist.data.gz | tr -d "[]" | sed 's:,$::g'
}

#---
##
## @Globals QUILL_TMP_DIR SPELL_NAME SPELL_SRC_URL SPELL_VERSION SPELL_LICENSE
## @Globals SPELL_SHORT_DESCRIPTION SPELL_URL SPELL_DEPENDENCIES BUILDISON
## @Globals DEPENDSISON QUILL_CPAN_INFO QUILL_CPAN_METADATA
#---
function quill_cpan_core()
{
  # so it is set even if we end prematurely, useful when adding spells
  # gets properly overwritten later on
  SPELL_NAME="$2"

  quill_get_manifests || return 1
  if zgrep -q -w -E "^$SPELL_NAME" $QUILL_TMP_DIR/02packages.details.txt.gz ||
     zgrep -q -w -E "^'$SPELL_NAME'" $QUILL_TMP_DIR/03modlist.data.gz
  then
    quill_get_cpan_meta $SPELL_NAME
    SPELL_NAME="$(sed -e 's/::/-/g' <<< "$SPELL_NAME")"
    SPELL_SRC_URL="http://www.cpan.org/authors/id/${QUILL_CPAN_INFO[2]}"
    SPELL_VERSION="${QUILL_CPAN_INFO[1]}"
    SPELL_SHORT_DESCRIPTION="${QUILL_CPAN_METADATA[6]}"
    SPELL_LICENSE="ART"
    SPELL_URL="http://search.cpan.org/~${QUILL_CPAN_METADATA[7]}/${SPELL_NAME}/"
    local description
    description="${QUILL_CPAN_METADATA[6]}"
    SPELL_NAME="${1//::/-}" # the lower case target wasn't manipulated yet
    echo $description > ${QUILL_TMP_DIR}/${SPELL_NAME}
    BUILDISON="BUILD, "
    touch ${QUILL_TMP_DIR}/${SPELL_NAME}-BUILD
    echo "default_build_perl" > ${QUILL_TMP_DIR}/${SPELL_NAME}-BUILD
    DEPENDSISON="DEPENDS, "
    SPELL_DEPENDENCIES="perl"
  else
    error_msg "Error: unable to find such a CPAN module"
    return 1
  fi

}

#---
##
## This software is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This software is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this software; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
##
#---

